name: Deploy QuickBooks Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build React app
      run: npm run build
    
    - name: Setup server directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo mkdir -p /var/www/quickbooks-integration-dashboard
          sudo chown $USER:$USER /var/www/quickbooks-integration-dashboard
          
          # Install Node.js if not present
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          
          # Install PM2 if not present
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
    
    - name: Copy project files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: "build/,server.js,package*.json,ecosystem.config.json"
        target: "/var/www/quickbooks-integration-dashboard/"
        overwrite: true
    
    - name: Install dependencies and restart app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/quickbooks-integration-dashboard
          npm ci --only=production
          
          # Start or restart the application
          if pm2 list | grep -q "quickbooks-dashboard"; then
            pm2 restart quickbooks-dashboard
          else
            pm2 start ecosystem.config.json
            pm2 save
            pm2 startup
          fi
          
          # Show status
          pm2 status
          echo "🚀 Deployment complete!"
          echo "🌐 Access at: http://${{ secrets.HOST }}:3001"